### PR TITLE
Got it to work using Connect

### LINKED ISSUE #25: Make middleware work with Connect
Is there any way or any plans to make this middleware work with Connect, which in turn works with Express? Haven't found a way to use Prerender, in any easy way, as a Connect middleware.

### PR DESCRIPTION
**Pull request by amiuhle**
Made the middleware Connect compatible. Fixes #25.

It does what it should do in my project using a grunt task for dev. I will fix the tests, just wanted to make sure you'll merge it before I do that.

### CODE REVIEW

**Comment by amiuhle** [comment]
Tests are working now!

**Comment by thoop** [comment]
Awesome! I'll have to look into this and run some scenarios locally soon before I merge. Thanks for doing that!

**Comment by amiuhle** [comment]
@thoop Yes, you should probably do some manual test scenarios apart from the unit tests.

**Comment by homeyer** [comment]
@amiuhle @scottcorgan, prerender-node should work with vanilla connect in 1.3.0 (PR #51 resolved it).

**Pull request closed without merging**
