### PR TITLE
Add SkypeUriPreview to crawlerUserAgents

### PR DESCRIPTION
**Pull request by tiblu**
Add SkypeUriPreview to crawlerUserAgents so that Skype could show beautiful previews.
prerender_skype_preview

### CODE REVIEW

**Comment by thoop** [comment]
Thanks!

**Comment by tiblu** [comment]
Any plans for the next release?

**Comment by thoop** [comment]
Yes, soon! Sorry for the delay.

**Comment by tiblu** [comment]
No problem, no rush as the config can be overridden.

**Pull request merged**
