### PR TITLE
Add flipboard to user agents

### PR DESCRIPTION
**Pull request by sumerion**
Add flipboard user agents to correctly render preview in the app.

### CODE REVIEW

**Comment by sumerion** [comment]
https://about.flipboard.com/browserproxy/

**Comment by thoop** [comment]
Thanks for that! We use a regex match so just `flipboard` will match both `flipboard` and `flipboardproxy`. Mind removing `flipboardproxy` from that list? I'll merge once that's removed.

**Comment by sumerion** [comment]
Sure. updated and removed flipboardproxy from the list.

**Comment by thoop** [comment]
Thanks!

**Pull request merged**
