### PR TITLE
Add Slack link expander user agent

### PR DESCRIPTION
**Pull request by chaselee**
See https://api.slack.com/robots

### CODE REVIEW

**Comment by chaselee** [comment]
@thoop, let me know if you have questions!

**Comment by thoop** [comment]
We are already checking for `slackbot`. Is that not doing the job?

**Comment by chaselee** [comment]
nope, slackbot is just the fallback when their other bots don't work. the main one is the slackbot-linkexpander, which is what's actually used for generating link previews inside of Slack. That's the one I've added here.

**Comment by thoop** [comment]
but we check for the existence of `slackbot` in the lowercase version of `Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)` which evaluates to true, right?

https://github.com/chaselee/prerender-node/blob/patch-5/index.js#L126

**Comment by chaselee** [comment]
true! didn't realize string partials were allowed. my bad!

**Comment by thoop** [comment]
No problem at all! Thanks for the PR

**Pull request closed without merging**
